#!/usr/bin/perl

# sizesort --- sort images to directories according to size.

# Copyright (C) 2003 Mark Probst

# Author: Mark Probst <schani@complang.tuwien.ac.at>
# Maintainer: Mark Probst <schani@complang.tuwien.ac.at>
# Version: 0.1

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2, or (at your option)
# any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program; if not, you can either send email to this
# program's maintainer or write to: The Free Software Foundation,
# Inc.; 675 Massachusetts Avenue; Cambridge, MA 02139, USA.

use strict;

die if ($#ARGV != 1);

my ($srcdir, $destdir) = @ARGV;

foreach my $filename (glob("$srcdir/*")) {
    if (-f $filename && -r $filename) {
	my ($w, $h) = split /\s+/, `imagesize $filename`;
	print "$filename $w $h\n";
	my $dir = sprintf "$destdir/%dx%d", $w, $h;
	`mkdir $dir` if (!-d $dir);
	`mv $filename $dir`;
    }
}
